### ISSUE TITLE
Visit 8 videos missing

### ISSUE THREAD

**Issue by silveycat** [ldp-uchicago/videos#8]
Hi Jason,

I'm browsing the videos and noticed that for a number of Project 2 subjects (22-92 as far as I can tell) the videos from visit 8 are missing. They don't show up in the folder either when I log in via Samba or using ssh. Any idea what's going on? Thanks a lot,

Cat

**Comment by joyrexus** [comment]
Oi! Oversight on my part when copying the videos over from the old video server.  I'm copying them over now.

Thanks for pointing this out!

**Comment by joyrexus** [comment]
Remaining session 8 videos were copied over.

**Comment by silveycat** [comment]
Great - thanks!
